
name : Add Repository
description : Submit your repository that needs a maintainer.
title : Repository Submission

labels:
    - Help Wanted

body:
    
    -
        type : input
        attributes:
            
            label : Repository
            description : The link to the repository.
            placeholder : https://github.com/<User>/<Repository>
            
            
        validations:
            required : true
    
    -
        type : input
        attributes:
            
            label : Language
            description : Programming languages used in the repository.
            placeholder : JS , CSS
            
        validations:
            required : true
        
    -
        type : checkboxes
        attributes:
            
            label : Transferable
            description : Can the repository be tranferred to another user / organization account?
            options:
                - label : Yes it can.
        
        validations:
            required : true
